//tealium universal tag - utag.1711 ut4.0.202207201238, Copyright 2022 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}}
return object;};u.map={"rtbh_hash":"hash","cp.utag_main_v_id":"user.id","rtbh_page_home":"page.home","rtbh_page_category":"page.category2","rtbh_expose_search":"offer.listing","rtbh_expose_view":"offer.id","rtbh_expose_favorite":"wishlist.add.id","rtbh_expose_conv_soft":"basket.add.id","rtbh_expose_conv_value":"order.value","rtbh_expose_conv_type":"order.type","rtbh_expose_conv_hard":"order.id","_sm_1711_12":"order.orderid"};u.extend=[function(a,b){try{b['_sm_1711_12']=new Date().getTime();}catch(e){utag.DB(e);}},function(a,b,c,d,e,f,g){if(1){d=b['dom.domain'];if(typeof d=='undefined')return;c=[{'www.immobilienscout24.de':'wvpeimwBknPqhgef8WQe'},{'www.immobilienscout24.at':'CaVD0XOUW7mgqEgcsdkG'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['rtbh_hash']=c[e][f];m=true};};if(m)break};if(!m)b['rtbh_hash']='';}},function(a,b){try{if(1){(function(){'use strict';var title=b.pag_pagetitle.replace(/^is24\.de\./,''),qp=b['qp.commercializationType']||'',add=qp?[qp]:[];if(title==='finden.wohnen.index'){b.rtbh_page_home=title;}
else{b.rtbh_page_category=[title].concat(add).join('.');}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){'use strict';if(a!=='view'){return;}
function diff(a,b){return b.filter(function(i){return!a.includes(i);});}
u.list_search_results=u.list_search_results||[];var searchresult=[];if(b.svc_module_name==='resultlist'){jQuery('ul[id*="resultListItems"] > li').each(function(){var $self=jQuery(this),id=$self.attr('data-id');if(id){searchresult.push(id);}});}
else if(b.svc_module_name==='com_listing_view_resultlist'){var result={};jQuery('a').filter(function(){return this.href.match(/expose\/[0-9]+\?referrer=com_otp_search/);}).each(function(){if(this.href.match(/\/([0-9]+)\?/)){result[RegExp.$1]=1;}});searchresult=searchresult.concat(Object.keys(result));}
if((searchresult=diff(u.list_search_results,searchresult)).length){u.list_search_results=[].concat(searchresult).sort();b.rtbh_expose_search=searchresult;}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){'use strict';if(!u.eventlistener_contact_provider){u.eventlistener_contact_provider=true;var evt=window.ontouchstart?'touchstart':'mousedown',pathname=document.location.pathname,expose_id="";if(/\/expose\/[0-9]+/.test(pathname)){b.rtbh_expose_view=expose_id=pathname.split('/').pop();jQuery(document.body).on(evt,'button:contains("Telefonnummer anzeigen"), button:contains("Anrufen")',function(){var data={};data.rtbh_expose_conv_soft=expose_id;data.rtbh_expose_conv_type='CALL';data.pag_pagetitle=utag.data.pag_pagetitle;utag.link(data,null,[u.id]);});jQuery(document.body).on(evt,'a:contains("Anbieter kontaktieren"), button:contains("E-mail")',function(){var data={};data.rtbh_expose_conv_soft=expose_id;data.rtbh_expose_conv_type='MESSAGE';data.pag_pagetitle=utag.data.pag_pagetitle;utag.link(data,null,[u.id]);});}}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){'use strict';if(!u.eventlistener_add_to_favorite){u.eventlistener_add_to_favorite=true;var evt=window.ontouchstart?'touchstart':'click';jQuery(document.body).on(evt,'[class*="is24-icon-heart"]',function(){var data={},$self=jQuery(this),favorite=[].slice.call(this.classList,0).includes("is24-icon-heart-favorite"),id=$self.data().id;if(!id){if(/expose\/[0-9]+$/.test(document.location.pathname)){id=document.location.pathname.split('/').pop();}}
if(id){if(favorite){data.rtbh_expose_favorite=id;data.pag_pagetitle=utag.data.pag_pagetitle;utag.link(data,null,[u.id]);}}});}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){"use strict";if(!u.eventlistener_conversion_hard){u.eventlistener_conversion_hard=true;var evt=window.ontouchstart?"touchstart":"mousedown",pathname=document.location.pathname,expose_id="",converted=false;if(/\/expose\/[0-9]+/.test(pathname)&&/gewerbe/.test(utag.data.pag_pagetitle)){expose_id=pathname.split("/").pop();jQuery(document.body).on(evt,'button:contains("Anrufen")',function(){setTimeout(function(){jQuery('ul[data-qa="contactPhoneNumbers"]')
.find('a[href*="tel"]')
.each(function(){jQuery(this).on("click",function(){var data={};data.rtbh_expose_conv_hard=expose_id;data.rtbh_expose_conv_type="CALL";data.pag_pagetitle=utag.data.pag_pagetitle;utag.view(data,null,[u.id]);});});},0);});jQuery(document.body).on(evt,'.contactform button[data-qa="sendButtonExtended"]',function(){setTimeout(function(){jQuery(this).on("click",function(){var data={};data.rtbh_expose_conv_hard=expose_id;data.rtbh_expose_conv_type=b['evt_ga_action'];data.pag_pagetitle=b['pag_pagetitle'];utag.view(data,null,[u.id]);});},0);});jQuery(document.body).one(evt,'a:contains("Anbieter kontaktieren")',function(){var start=new Date().getTime();(function wait(waitFor,snooze,retries){retries=retries||0;var $target=jQuery(waitFor);if($target.length){if(/contactConfirmation/.test(document.URL)){var data={},end=new Date().getTime(),time=(end-start)/1000;data.rtbh_expose_conv_hard=expose_id;data.rtbh_expose_conv_type="MESSAGE";data.rtbh_time_to_complete=time;data.pag_pagetitle=utag.data.pag_pagetitle;utag.view(data,null,[u.id]);}}else{setTimeout(function(){wait(waitFor,snooze,++retries);},snooze);}
})('div[data-qa="successMessage"]',1000);});}}})();}}catch(e){utag.DB(e)}}];u.loader_cb=function(a,b,c){utag.DB("send:1711:CALLBACK");u.initialized=true;utag.DB("send:1711:CALLBACK:COMPLETE");};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};u.key="__rtbhouse.lid";u.lid=window.localStorage.getItem(u.key);if(!u.lid){u.lid="";u.pool="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(var i=0;i<20;i++){u.lid+=u.pool.charAt(Math.floor(Math.random()*u.pool.length));}
window.localStorage.setItem(u.key,u.lid);}
u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:1711");utag.DB(b);var rtbhTags,c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","hash":"","prefix":"","base_url":"creativecdn.com/tags","user":{"id":"unknown"},"page":{"home":"","category2":""},"offer":{"listing":[],"id":""},"wishlist":{"add":{"id":""}},"basket":{"add":{"id":""}},"order":{"orderid":"","type":"unknown","value":"1.0","id":""}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};utag.DB("send:1711:EXTENSIONS");utag.DB(b);rtbhTags=[];c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.map_func(e[f].split("."),u.data,b[d]);}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){u.data.event=u.data.event.concat(u.map[d].split(","));}}}}
utag.DB("send:1711:MAPPINGS");utag.DB(u.data);if(!u.data.user.id){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
if(a==="view"){if(u.data.page.home){rtbhTags.push(["pr",u.data.hash,"home"].join("_"));}
else if(u.data.page.category2){rtbhTags.push(["pr",u.data.hash,"category2",u.data.page.category2].join("_"));}
if(u.data.offer.listing.length){rtbhTags.push(["pr",u.data.hash,"listing",u.data.offer.listing.join(",")].join("_"));}
if(u.data.offer.id){rtbhTags.push(["pr",u.data.hash,"offer",u.data.offer.id].join("_"));}
if(u.data.order.orderid){if(u.data.order.id){c.push('cd=default');rtbhTags.push(["pr",u.data.hash,"orderstatus2",u.data.order.value,[u.data.order.type,u.data.order.orderid].join('-'),u.data.order.id].join("_"));}}
if(document.location.pathname=="/meinkonto/after-payment/"){rtbhTags.push(["pr",u.data.hash,"basketadd",Date.now()+""+Math.random().toFixed(8).substring(2),].join("_"));}}
else if(a==="link"){if(u.data.wishlist.add.id){rtbhTags.push(["pr",u.data.hash,"wishlist",u.data.wishlist.add.id].join("_"));}
if(u.data.basket.add.id){rtbhTags.push(["pr",u.data.hash,"basketadd",u.data.basket.add.id].join("_"));}}
if(rtbhTags.length){rtbhTags=[["pr",u.data.hash,"uid",u.data.user.id].join("_")].concat(rtbhTags);for(var i=0;i<rtbhTags.length;i++){c.push("id="+encodeURIComponent(rtbhTags[i]));}
c.push("su="+encodeURIComponent(document.location.href?document.location.href:""));c.push("sr="+encodeURIComponent(document.referrer?document.referrer:""));c.push("ts="+encodeURIComponent(""+Date.now()));var iframecount=document.querySelectorAll('[id*="utag_1711"]').length+1;u.loader({"type":"iframe","src":["https://",u.data.prefix,u.data.base_url,"?type=iframe","&",c.join(u.data.qsp_delim)].join(""),"cb":u.loader_cb,"loc":"body","id":"utag_1711-"+iframecount,"attrs":{"width":"1","height":"1","scrolling":"no","frameBorder":"0","style":"display:none","referrerpolicy":"no-referrer-when-downgrade"}});}
utag.DB("send:1711:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("1711","immobilienscout.is24"));}catch(error){utag.DB(error);}
