//tealium universal tag - utag.1877 ut4.0.202307171023, Copyright 2023 Tealium.com Inc. All Rights Reserved.
window.rtbhEvents=window.rtbhEvents||[];try{(function(id,loader){var u={id:id};utag.o[loader].sender[id]=u;u.ev={view:1,link:1};u.initialized=false;u.scriptrequested=false;u.EVENTS_LIST={category:'category',offer:'offer',wishlist:'wishlist',size:'size',listing:'listing',basketadd:'basketadd',basketstatus:'basketstatus',conversion:'conversion'};u.toBoolean=function(val){val=val||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";};u.clearEmptyKeys=function(object){Object.keys(object).forEach(function(key){if(object[key]===''||object[key]===undefined){delete object[key];}});return object;};u.mapFunc=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.mapFunc(arr,obj[i],item);}else{obj[i]=item;}};u.callback=function(){var eventObject;u.data.events.forEach(function(eventName){switch(eventName){case u.EVENTS_LIST.category:{eventObject={eventType:eventName,categoryId:u.data.categoryId};break;}
case u.EVENTS_LIST.offer:case u.EVENTS_LIST.wishlist:case u.EVENTS_LIST.basketadd:{eventObject={eventType:eventName,offerId:u.data.offerId};break;}
case u.EVENTS_LIST.size:{eventObject={eventType:eventName,size:u.data.size};break;}
case u.EVENTS_LIST.listing:case u.EVENTS_LIST.basketstatus:{eventObject={eventType:eventName,offerIds:u.data.offerIds};break;}
case u.EVENTS_LIST.conversion:{eventObject={eventType:eventName,conversionClass:u.data.conversionClass,conversionSubClass:u.data.conversionSubClass,conversionId:u.data.conversionId,conversionValue:u.data.conversionValue,offerIds:u.data.offerIds,};break;}
default:{eventObject={eventType:eventName};}}
utag.ut.merge(u.clearEmptyKeys(eventObject),u.data[eventName],1);window.rtbhEvents.push(eventObject);});};u.map={"rtbh_hash":"tagging_hash","cp.utag_main_v_id":"user_id","rtbh_page_home":"page_home","rtbh_page_category":"page_category2","rtbh_expose_search":"offer_listing","rtbh_expose_view":"offer_id","rtbh_expose_favorite":"wishlist_add.id","rtbh_expose_conv_soft":"basket_add.id","rtbh_expose_conv_value":"order_value","rtbh_expose_conv_type":"order_type","rtbh_expose_conv_hard":"order_id","_sm_1877_12":"order_orderid"};u.extend=[function(a,b){try{b['_sm_1877_12']=new Date().getTime();}catch(e){utag.DB(e);}},function(a,b,c,d,e,f,g){if(1){d=b['dom.domain'];if(typeof d=='undefined')return;c=[{'www.immobilienscout24.de':'wvpeimwBknPqhgef8WQe'},{'www.immobilienscout24.at':'CaVD0XOUW7mgqEgcsdkG'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['rtbh_hash']=c[e][f];m=true};};if(m)break};if(!m)b['rtbh_hash']='';}},function(a,b){try{if(1){(function(){'use strict';var title=b.pag_pagetitle.replace(/^is24\.de\./,''),qp=b['qp.commercializationType']||'',add=qp?[qp]:[];if(title==='finden.wohnen.index'){b.rtbh_page_home=title;}
else{b.rtbh_page_category=[title].concat(add).join('.');}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){'use strict';if(a!=='view'){return;}
function diff(a,b){return b.filter(function(i){return!a.includes(i);});}
u.list_search_results=u.list_search_results||[];var searchresult=[];if(b.svc_module_name==='resultlist'){jQuery('ul[id*="resultListItems"] > li').each(function(){var $self=jQuery(this),id=$self.attr('data-id');if(id){searchresult.push(id);}});}
else if(b.svc_module_name==='com_listing_view_resultlist'){var result={};jQuery('a').filter(function(){return this.href.match(/expose\/[0-9]+\?referrer=com_otp_search/);}).each(function(){if(this.href.match(/\/([0-9]+)\?/)){result[RegExp.$1]=1;}});searchresult=searchresult.concat(Object.keys(result));}
if((searchresult=diff(u.list_search_results,searchresult)).length){u.list_search_results=[].concat(searchresult).sort();b.rtbh_expose_search=searchresult;}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){'use strict';if(!u.eventlistener_contact_provider){u.eventlistener_contact_provider=true;var evt=window.ontouchstart?'touchstart':'mousedown',pathname=document.location.pathname,expose_id="";if(/\/expose\/[0-9]+/.test(pathname)){b.rtbh_expose_view=expose_id=pathname.split('/').pop();jQuery(document.body).on(evt,'button:contains("Telefonnummer anzeigen"), button:contains("Anrufen")',function(){var data={};data.rtbh_expose_conv_soft=expose_id;data.rtbh_expose_conv_type='CALL';data.pag_pagetitle=utag.data.pag_pagetitle;utag.link(data,null,[u.id]);});jQuery(document.body).on(evt,'a:contains("Anbieter kontaktieren"), button:contains("E-mail")',function(){var data={};data.rtbh_expose_conv_soft=expose_id;data.rtbh_expose_conv_type='MESSAGE';data.pag_pagetitle=utag.data.pag_pagetitle;utag.link(data,null,[u.id]);});}}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){'use strict';if(!u.eventlistener_add_to_favorite){u.eventlistener_add_to_favorite=true;var evt=window.ontouchstart?'touchstart':'click';jQuery(document.body).on(evt,'[class*="is24-icon-heart"]',function(){var data={},$self=jQuery(this),favorite=[].slice.call(this.classList,0).includes("is24-icon-heart-favorite"),id=$self.data().id;if(!id){if(/expose\/[0-9]+$/.test(document.location.pathname)){id=document.location.pathname.split('/').pop();}}
if(id){if(favorite){data.rtbh_expose_favorite=id;data.pag_pagetitle=utag.data.pag_pagetitle;utag.link(data,null,[u.id]);}}});}}());}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){"use strict";if(!u.eventlistener_conversion_hard){u.eventlistener_conversion_hard=true;var evt=window.ontouchstart?"touchstart":"mousedown",pathname=document.location.pathname,expose_id="",converted=false;if(/\/expose\/[0-9]+/.test(pathname)&&/gewerbe/.test(utag.data.pag_pagetitle)){expose_id=pathname.split("/").pop();jQuery(document.body).on(evt,'button:contains("Anrufen")',function(){setTimeout(function(){jQuery('ul[data-qa="contactPhoneNumbers"]')
.find('a[href*="tel"]')
.each(function(){jQuery(this).on("click",function(){var data={};data.rtbh_expose_conv_hard=expose_id;data.rtbh_expose_conv_type="CALL";data.pag_pagetitle=utag.data.pag_pagetitle;utag.view(data,null,[u.id]);});});},0);});jQuery(document.body).on(evt,'.contactform button[data-qa="sendButtonExtended"]',function(){setTimeout(function(){jQuery(this).on("click",function(){var data={};data.rtbh_expose_conv_hard=expose_id;data.rtbh_expose_conv_type=b['evt_ga_action'];data.pag_pagetitle=b['pag_pagetitle'];utag.view(data,null,[u.id]);});},0);});jQuery(document.body).one(evt,'a:contains("Anbieter kontaktieren")',function(){var start=new Date().getTime();(function wait(waitFor,snooze,retries){retries=retries||0;var $target=jQuery(waitFor);if($target.length){if(/contactConfirmation/.test(document.URL)){var data={},end=new Date().getTime(),time=(end-start)/1000;data.rtbh_expose_conv_hard=expose_id;data.rtbh_expose_conv_type="MESSAGE";data.rtbh_time_to_complete=time;data.pag_pagetitle=utag.data.pag_pagetitle;utag.view(data,null,[u.id]);}}else{setTimeout(function(){wait(waitFor,snooze,++retries);},snooze);}
})('div[data-qa="successMessage"]',1000);});}}})();}}catch(e){utag.DB(e)}}];u.send=function(utag_event,data_layer){if(!u.ev[utag_event]&&u.ev.all===undefined){utag.DB('send:1877:EVENT NOT SUPPORTED:COMPLETE');return;}
utag.DB('send:1877');utag.DB(data_layer);var a,b,c,d,e,f,g,h,query_params;a=utag_event;b=data_layer;u.data={qsp_delim:'&',kvp_delim:'=',base_url:'https://tags.creativecdn.com/##utag_tagging_hash##.js',tagging_hash:"",region:"emea",eventType:'',categoryId:'',offerId:'',size:'',offerIds:'',conversionClass:'',conversionSubClass:'',conversionId:'',conversionValue:'',order_id:'',order_subtotal:'',product_id:[],product_category:[],custom:{},events:[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};utag.DB('send:1877:EXTENSIONS');utag.DB(data_layer);query_params=[];Object.keys(utag.loader.GV(u.map)).forEach(function(mapping_key){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==''){var destinations=u.map[mapping_key].split(',');destinations.forEach(function(parameter){u.mapFunc(parameter.split('.'),u.data,data_layer[mapping_key]);});}else{var event_destinations=mapping_key.split(':');if(event_destinations.length===2&&String(data_layer[event_destinations[0]])===String(event_destinations[1])){if(u.map[mapping_key]){u.data.events=u.data.events.concat(u.map[mapping_key].split(','));}}}});utag.DB('send:1877:MAPPINGS');utag.DB(u.data);var eCommerceMapping=[{eCommerceData:data_layer._corder,name:'conversionId',isArray:false},{eCommerceData:data_layer._ctotal,name:'conversionValue',isArray:false},{eCommerceData:data_layer._cprod,name:'offerId',isArray:true},{eCommerceData:data_layer._ccat,name:'categoryId',isArray:true}];eCommerceMapping.forEach(function(dataObject){if(!dataObject.isArray){u.data[dataObject.name]=u.data[dataObject.name]||dataObject.eCommerceData||'';}else if(u.data[dataObject.name].length===0&&dataObject.eCommerceData!==undefined&&dataObject.isArray){u.data[dataObject.name]=dataObject.eCommerceData.slice(0);}});if(!u.data.tagging_hash){utag.DB(u.id+': Tag not fired: Required attribute tagging_hash not populated');return;}
u.data.base_url=u.data.base_url.replace("##utag_tagging_hash##",u.data.tagging_hash);if(u.initialized){u.callback();}else{if(!u.scriptrequested){u.scriptrequested=true;window.rtbhEvents.push({eventType:'init',value:u.data.tagging_hash,dc:u.data.region});utag.ut.loader({type:'script',src:u.data.base_url,cb:u.callback,loc:'script',id:'utag_1877',attrs:{}});}}
utag.DB('send:1877:COMPLETE');};utag.o[loader].loader.LOAD(id);}('1877','immobilienscout.is24'));}catch(error){utag.DB(error);}
